version: "3.9"
services:
  grafana:
    build:
        context: ./grafana
        dockerfile: Dockerfile
    container_name: grafana_container
    restart: always
    ports:
      - 3003:3000
    depends_on:
      - clickhouse_db
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources-ch.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=vertamedia-clickhouse-datasourc


  int-collector:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    privileged: true
    tty: true
    network_mode: "host"
    environment:
      - INFLUX_PORT= 8086
      - INFLUX_ADDRESS= influxdb
      - IFACE= 'eth0'
      - INT_PORT= 8090
      - DATABASE_NAME= 'int_telemetry_db'
      - PERIOD= 1
      - EVENT_PERIOD= 0
      - THRESHOLDS_SIZE= '50 50 50 50 50 100'
      - LOG_LEVEL= 20
      - LOG_RAPORTS_LEVEL= 20
    volumes:
      - /lib/modules:/lib/modules:ro
      - /etc/localtime:/etc/localtime:ro

  clickhouse_db:
     container_name: clickhouse_db_container
     image: yandex/clickhouse-server:21.5.6.6
     ports:
        - "8123:8123"
        - "9000:9000"
     depends_on:
      - int-collector
     volumes:
         - ./clickhouse:/docker-entrypoint-initdb.d/
